/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Maths {
   
	public int suma(int a, int b) {
		return a + b;
	}
	
	public int resta(int a, int b) {
		return a - b;
	}
}
